// angular/starWarsApp/src/app/components/heroes/hero/hero.component.ts
import { Component,Input } from "@angular/core";
import {Hero} from "./hero.model";

@Component({
  selector: "hero",
  templateUrl: "./hero.component.html",
  styleUrls: ["./hero.component.css"],
})

export class HeroComponent{
  @Input() hero:Hero;
}


<div class="hero">
   <div class="hero__details">
      <div class="detail detail--name">
         <label>{{hero.name}}</label>
       </div>
      <div class="detail detail--gender">
        <label>Gender: </label>
        <span>{{hero.gender}}</span>
      </div>
      <div class="detail detail--hairColor">
        <label>Hair color: </label>
        <span>{{hero.hair_color}}</span>
      </div>
      <div class="detail detail--mass">
        <label>Mass: </label>
        <span>{{hero.mass}}</span>
      </div>
      <div class="detail detail--skinColor">
        <label>Skin color: </label>
        <span>{{hero.skin_color}}</span>
      </div>
    </div>
</div>

// react/starWarsApp/src/components/heroes/hero/hero.component.jsx
import React from "react";
import ItemCard from "../../../common/components/item-card";

const Hero = ({ personalData,className }) => (
  <ItemCard title={personalData.name} className={`ItemCard ${className}`}>
    <div className="ItemCard__details">
      <div className="detail detail--gender">
        <label>Gender: </label>
        <span>{personalData.gender}</span>
      </div>
      <div className="detail detail--hairColor">
        <label>Hair color: </label>
        <span>{personalData.hair_color}</span>
      </div>
      <div className="detail detail--mass">
        <label>Mass: </label>
        <span>{personalData.mass}</span>
      </div>
      <div className="detail detail--skinColor">
        <label>Skin color: </label>
        <span>{personalData.skin_color}</span>
      </div>
    </div>
  </ItemCard>
);

export default Hero;
